### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by audy** [sjackman/fastascripts#1]
Could you add an open source license?

**Comment by sjackman** [comment]
Done. Which script(s) are you using? I hope you read the disclaimer:

> These scripts were never meant to see the light of day. I apologize for the distasteful code.

**Comment by audy** [comment]
Just `falength` and `farename`.

I like the awk/perl hacks!

**Comment by sjackman** [comment]
Have you used [bioawk](https://github.com/lh3/bioawk)?

### Print lengths

``` sh
bioawk -cfastx '{print length($seq)}' sample.fa
```

### Renumber sequences

``` sh
bioawk -cfastx '{print ">" i++ "\n" $seq}' sample.fa
```
