### ISSUE TITLE
issues about running abyss-fatoagp.pl

### ISSUE THREAD

**Issue by wuxiaopei0509** [sjackman/fastascripts#2]
Dear ,
I used abyss-fatoagp.pl to Convert a FASTA file of scaffolds to a FASTA file of contigs and an AGP file.However，it occured errors as follws.Could you help me with the issues?Thank you very much!
![图片](https://user-images.githubusercontent.com/52643750/65137482-01869180-da3c-11e9-8108-a7c708e9b9e9.png)

**Comment by sjackman** [comment]
That script `abyss-fatoagp` is distributed with ABySS. https://github.com/bcgsc/abyss/blob/master/bin/abyss-fatoagp
Please open an issue at https://github.com/bcgsc/abyss/issues. Please include the complete command that you typed in, and copy and paste the complete error message text (not a screenshot please).
